[theme]
primaryColor = "#82ca9d"
backgroundColor = "#1e1e24"
secondaryBackgroundColor = "#2d2d38"
textColor = "#f4f4f9"
font = "sans serif"

[sidebar]
showSidebarNavigation = true

[layout]
pageLayout = "wide"

